# Generated by Django 5.1.2 on 2024-10-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_event_available_seat_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
