# Generated by Django 5.1.2 on 2024-10-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('eventapp', '0004_remove_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(default='concert', to='categories.categorie'),
        ),
    ]
